### ISSUE TITLE
Drag doesn't work correctly in specific case

### ISSUE THREAD

**Issue by svitlanaAntoniuk** [luckylooke/dragular#113]
Here is code example:
https://jsfiddle.net/hLsuege1/43/

If you are trying to drag items after "New object" button click - items disappear.

**Comment by luckylooke** [comment]
I have updated your fiddle: https://jsfiddle.net/luckylooke/hLsuege1/44/ now it works.
You cannot replace the items with new array, because the dragular keeps reference to the original one, the one you provided on init. So you need to update existing by pushing new values in it. This seems to be common problem here, so I am wondering about solution and I think I have one, I will include it in next release.

**Comment by svitlanaAntoniuk** [comment]
Thanks for response.
