### ISSUE TITLE
lockY and lockX enhancement

### ISSUE THREAD

**Issue by JerimSD** [luckylooke/dragular#134]
Hi,

I'm using the lockY and lockX options in a nested structure of rows and columns. Rows can be reorganized between them. Columns can be reorganized between them or moved to another row (acting as columns containers).
The lockY option looks great on the rows, but the lockX option on the columns could be improve.

When I'm moving a Column from its original container to another one, the lockX option locks the item on its original container, even though I can actually drop the column in another one.

Here's an example of this situation : https://plnkr.co/edit/IXrBAS0qquhIGhT1cnZP

lockX could be enhanced in such a way that whenever I move an item with lockX option to another container the lockX option isn't applied on the source container anymore but on the target one.
The same logic could be applied to lockY.

What do you think about this idea ? Do you think its possible ?

**Comment by luckylooke** [comment]
I will look at this soon.. thanks for report 👍

**Comment by luckylooke** [comment]
In my opinion it could not be allowed to drop item outside the container, I will try to solve it, but my first thoughts are telling me that this is problem of core implementation. Because position of mouse is tested, and not the actual dragged item :/ 

> lockX could be enhanced in such a way that whenever I move an item with lockX option to another container the lockX option isn't applied on the source container anymore but on the target one.
> The same logic could be applied to lockY.
I see... but I am not developing new features right now, because I am developing much better dnd lib, I hope that better than dragula. For now I am only fixing bugs.. I will rewrite dragular by replacing core codebase with new lib after finishing it. Thanks for understanding.

**Comment by luckylooke** [comment]
I know it is not correct and best solution, it is kind of hack but it works, you can use [options.accept](https://github.com/luckylooke/dragular#optionsaccepts) or [options.canBeAccepted](https://github.com/luckylooke/dragular#optionscanbeaccepted) to prevent items being dropped elsewhere (out of the bounding box).
