### ISSUE TITLE
Dragged item invalid when filter

### ISSUE THREAD

**Issue by vegeanfire** [luckylooke/dragular#159]
Here is my case (i cannot re-produce it on Jsfiddle)
I have 3 columns which apply dragular:

**1st column (column A)** place several items which can be copied into 3rd column (column C). It has a filter input which can filter item by name.

**2st column (column B)** place the group items which contains items in column C. When i select each item in column B it loads the items in column C.

**3rd column (column C)** place the items of selected group item in column B.

When i pick an item in column B, it loads items in column C, and then type to filter column A, then drag it into column C. But it only works with 1st item in column B, for others, they invalid

it exposes the error: Cannot read property "parentNode" of null

**Comment by luckylooke** [comment]
> i cannot re-produce it on Jsfiddle
why? 

Please check how you update models representing containers, it is common mistake, since javascript uses references and you provide models on dragular init, you cannot replace them on update. You need to edit them instead. 

But I can only a guess what is the problem if you cannot reproduce it. Try to fork this [codepen](https://codepen.io/luckylooke/pen/pPmeWY) for reproduction.
