### ISSUE TITLE
Get sort order index

### ISSUE THREAD

**Issue by igorpejic** [luckylooke/dragular#28]
A feature of dragular is that:  it "Figures out sort order on its own". Is there any way to get the variables based on which the order is determined?
I need it because I save object positions in my database.
Thank you.

**Comment by luckylooke** [comment]
Yes, if you render items with ngRepeat and provide items model (array) via ```options.containersModel``` to dragular. Model is sorted same way as DOM items representations.

**Comment by igorpejic** [comment]
Unfortunately I am getting error: 
```
Uncaught TypeError: 
$rootScope.$applyAsync is not a functionmoveInContainersModel @ dragularService.js:725
drag @ dragularService.js:680
n.event.dispatch @ jquery.min.js:3
n.event.add.r.handle @ jquery.min.js:3
```
Meanwhile we found a way to update the position in another way directly in the DOM. 
If I will need `options.containersModel` again, I will dig into it, but for now it is good.
Thank you.

**Comment by jameswyse** [comment]
That's a weird one. Are you using Angular 1.2.x? `$applyAsync` was added in 1.3.

**Comment by igorpejic** [comment]
@jameswyse Yes, I am using Angular 1.2.X. That's the catch. 
Thank you very much. 
You can close this issue now if you want.

**Comment by jameswyse** [comment]
@luckylooke You can wrap your scope changes in a function and pass it to `$applyAsync` as an argument instead of calling it at the end with no arguments, that way angular will handle any errors for free (`try`/`catch`) and also ensure the digest cycle runs (in a `finally`) - at least that's the case for `$apply`, I assume it's the same with `$applyAsync` :)

`$rootScope.$applyAsync(function () { // update scope });`

**Comment by luckylooke** [comment]
@jameswyse Ok, I will rewrite it that way :+1:

**Comment by jameswyse** [comment]
@igorpejic ah that's a shame. It's definitely worth upgrading to 1.3/1.4 if you can, there's some pretty huge performance benefits in 1.3 :)
