### ISSUE TITLE
use model reference instead of DOM index

### ISSUE THREAD

**Issue by driannaude** [luckylooke/dragular#48]
I think it would be a good idea to reference the model data directly, rather than an index from the DOM, which will take care of issues like reference mismatches in filtered lists, as well as being able to reference the model data when events are emitted. I haven't really thought about implementation, just making the suggestion at this stage. Are you still actively maintaining this @luckylooke, or have you shifted focus to Nicolas' `angular-dragula`? The API for `dragular` seems much sane-r than `angular-dragula`, I kinda prefer `dragular` to be honest :smile_cat:

**Comment by luckylooke** [comment]
I havent much time for open source last weeks. But I will try to update it soon. Thanks for the idea, I will look at it, and let you know the results here. Thanks for you preference and friendly words :)

**Comment by luckylooke** [comment]
I am planning to make huge refactor (code readability and documentation), I will check possibility to implement your idea, because it sounds good to me. About issues with filtered lists, you can use reference to filtered collection object instead of direct model reference.
Such like this: ```<tr ng-repeat="phone in (filteredPhones = (phones | filter: query))">```
Link: http://stackoverflow.com/questions/16050533/how-can-i-obtain-the-result-array-of-an-angular-filter-expression-in-a-varia

But I know your suggested feature could be nicer solution ;) I will see..

**Comment by luckylooke** [comment]
I was wondering about solution of references model and my thoughts leaded me to a problem. You cannot reference primitive values and model can be array of primitive values. But this also leaded me to thought that probably my previous suggested solution should not work too. I definitely must come with new solution of filtered ng-repeats.. ;)
