### ISSUE TITLE
Doesn't work with IE11

### ISSUE THREAD

**Issue by piyushkhanna** [luckylooke/dragular#68]
When using on IE11, console shows no errors but drag and drop just doesn't work. Attaching my solution. 
[DragulaTest.zip](https://github.com/luckylooke/dragular/files/135243/DragulaTest.zip)

**Comment by luckylooke** [comment]
Ok, I will look at it soon. Thanks

**Comment by luckylooke** [comment]
I know, I know it is not "soon" at all, mostly because I hate IE related bugs.. I am so sorry... BUT now it is done (in dev branch). IE still reports "Error: Invalid argument" on the beginning, but I cant find why. Since it everything seems to be working, I will investigate it more somewhere in future. Thanks for you contribution and your infinite patience! :+1:

**Comment by piyushkhanna** [comment]
Thanks!
