### ISSUE TITLE
Bad redraw on refill array of items

### ISSUE THREAD

**Issue by joujo1212** [luckylooke/dragular#70]
Use case: Put some items to dragular, than I get some changes back, what mean assign different array of items to dragular. For a second is showing item from both arrays. What am I doing wrong? I tried delete previous version of array, but without changes. Maybe bug in dragular? 

In GIF are 2 items at first time, than I put one away by assign previous version of array. For a second there are 3 items - 2 from previous version and 1 from actual version.

![dragular redraw list problem](https://cloud.githubusercontent.com/assets/6673146/13568843/8f53aca4-e464-11e5-9cae-f775a12aa1b6.gif)

**Comment by luckylooke** [comment]
Once you provide array of items to dragular you cannot replace it, because dragular will lost reference. You need to edit same array you provided on initialisation. So if you want to clean the array, use `myArray.length = 0` and then if you wish to fill it with new data, you can push into array new values. This is going to be change in future as many user ask for it. Let me know if your problem was solved, thanks ;)

**Comment by luckylooke** [comment]
Seems to be no more actual..
