### ISSUE TITLE
Displays random item in the destination container, when dragged from a filtered array source

### ISSUE THREAD

**Issue by m-kumaran** [luckylooke/dragular#82]
Hi

First of all, thank you for this nice library.

I have come across the following issue when I tried with a filtered array source
using containersFilteredModel.

I wanted a toggle filter which dynamically filters the source container, and can be dragged to a destination container.
I used a function based filter on the source array during the toggle.  This works fine.
But when I toggle and get the filtered items and when dragged to the destination container, it shows a random item from the unfiltered item.

Please find the following jsfiddle link:-

http://jsfiddle.net/nrjh7057/13/
(I have simulated the toggle as an input text in this jsFiddle so that we can type ODD/EVEN)

Thanks in advance.

**Comment by luckylooke** [comment]
Ok, I will look at it soon.. there is probably something wrong with filteredModels now as reported in #83. So maybe solving #83 will also solve your issue. Thanks for reporting issue and for using dragular ;)

**Comment by luckylooke** [comment]
Ok.. it was not related to #83.. you have typo in dragularService options:
Instead of `containersFilteredItems` there must be `containersFilteredModel`, after correction it seems to be working fine
http://jsfiddle.net/9w9bvgvd/

But your function filteredItems() is running redundantly more times than needed, I think better approach could be:
http://jsfiddle.net/fyp09dy4/

Have a nice day ;)

**Comment by m-kumaran** [comment]
Excellent, now it works with that change.  Cheers :)

PS: Somehow the first link (http://jsfiddle.net/9w9bvgvd/)  didn't work, but the second one works fine.

Have a nice day!

**Comment by luckylooke** [comment]
What is wrong with first link? It seems to be working for me :eyes:
