### ISSUE TITLE
After updating the 'containersModel' the drag&drop becames incoherent

### ISSUE THREAD

**Issue by slimovic** [luckylooke/dragular#90]
Hello there,

Every time, I update the model(in my example the array is **items**), in my case the new data from the backend(in the example I added a Timeout), the drag & drop becames incoherent; when I drag an element or an item it disappear from the list.

This is the [example](https://plnkr.co/edit/6RnFQDC28OdieUd9eXbJ?p=preview).

P.S: Wait 2 seconds before to drag and drop.

**Comment by luckylooke** [comment]
It is because dragular has lost its referenced array you provided before, at init.. instead of replacing reference in vm.items you need to edit/update it. I have edited your plunker to show you what I mean https://plnkr.co/edit/mIZrYFnogfEKm8GAQYBV?p=preview. Hope you understand the problem, otherwise you can ask for additional info. Thanks ;)

**Comment by atsoy** [comment]
@luckylooke I've got same problem with updated list of elements. I've also used `$applyAsync.`

And it works till the first move. After dropping next element I receive:
- `Uncaught TypeError: Cannot read property 'nextElementSibling' of null`
After 2nd move- `Uncaught TypeError: Cannot read property 'parentNode' of null`.

Have same html structure as [here](http://plnkr.co/edit/BGt1c4XBLzLqesg1zDWd?p=preview), just with 3 differences: 
-  initially i have my list array which i pass into child-directive, where dragular is.
-  list management done outside of child directive, where dragular used.
-  and as i mentioned before i upload list from localStorage, when i want to reset to initialState.
